spring.datasource.username=root
spring.datasource.password=cometrue
spring.mail.username=meongkune@gmail.com
spring.mail.password=irvmhoeajnnymqcc
jwt.secret=yNtqhQ7oQbinvY7nHqE7CfTMlWuFA1R/EqO4U3eYRt8=