spring.datasource.username=root
spring.datasource.password=1234
spring.mail.username=sungchan0820@gmail.com
spring.mail.password=tuikizxkvchpikpp
jwt.secret=yNtqhQ7oQbinvY7nHqE7CfTMlWuFA1R/EqO4U3eYRt8=